### ISSUE TITLE
大きさの変更に伴うPossibleActionの変更

### ISSUE THREAD

**Issue by Light606F** [pigooosuke/gym_reversi#1]
お世話になっております．

ボードの大きさを変更した際にPossibleActionが変更されないことを発見しました．

238行目
`
                            actions.append(pos_x*8+pos_y)`
の8はdではないでしょうか．

取り急ぎ報告までに．失礼しました．

**Comment by Light606F** [comment]
Reset関数についても以下のとおりです．

```
        centerL = int(self.board_size/2-1)
        centerR = int(self.board_size/2)
        self.state[2, :, :] = 1.0
        self.state[2, (centerL):(centerR+1), (centerL):(centerR+1)] = 0
        self.state[0, centerR, centerL] = 1
        self.state[0, centerL, centerR] = 1
        self.state[1, centerL, centerL] = 1
        self.state[1, centerR, centerR] = 1
```

**Comment by pigooosuke** [comment]
issueを見逃しており、対応が遅れましたmm
reportありがとうございます修正を加えました。
https://github.com/pigooosuke/gym_reversi/commit/1ddbd04c82f7eda6eebcbb279c2fc02d42dcd84d
