### ISSUE TITLE
numpyのバージョンについて

### ISSUE THREAD

**Issue by shinchankosen** [pigooosuke/gym_reversi#4]
こんにちは、shinchankosenと申します。
qiitaのサイトを読ませていただき、こちらのレポジトリをforkしていじって遊ぼうとしていたところ、実行できなかったので、修正した点について報告させていただきます。

つきましては、以下の3点の修正および疑問を提案します。

- reversi.pyのmake_random_policy内のnp_random.randintを、np_random.integersに変更。(randintはおそらくnumpyのバージョンの問題で、ないと吐かれる。) 
       - https://github.com/ray-project/ray/issues/24133 こちらを参考にしてintegersに変更すると実行できました。
- 同じところのd ** 2 + 1のdは宣言されていないです
- 出力がずれており、outfile.write(' ' * 6)の6を7にすると改善します

2,3つ目は修正しなくても実行に問題はないです。

よろしくお願いします。

**Comment by pigooosuke** [comment]
@shinchankosen 
報告ありがとうございます。先程修正致しましたー。
https://github.com/pigooosuke/gym_reversi/pull/5

**Comment by shinchankosen** [comment]
迅速な対応ありがとうございました！
